[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.5.2"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
