---
metrics:
  - name: Activity repo groups
    series_name_or_func: multi_row_single_column
    sql: activity_repo_groups
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
  - name: All PRs merged
    series_name_or_func: all_prs_merged
    sql: all_prs_merged
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
  - name: Github Stats by Repository Group
    series_name_or_func: multi_row_single_column
    sql: github_stats_by_repo_groups
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
    merge_series: gh_stats_rgrp
  - name: Github Stats by Repository
    series_name_or_func: multi_row_single_column
    sql: github_stats_by_repos
    periods: h,d,w,m,q,y
    aggregate: 1,7,24
    skip: h7,w7,m7,q7,y7,d24,w24,m24,q24,y24
    multi_value: true
    merge_series: gh_stats_r
  - name: SIG mentions breakdown by categories using text
    series_name_or_func: multi_row_single_column
    sql: sig_mentions_breakdown
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: PRs labels by repository groups
    series_name_or_func: multi_row_single_column
    sql: prs_labels
    periods: d
    multi_value: true
  - name: Time opened to merged (number of hours)
    series_name_or_func: multi_row_multi_column
    sql: opened_to_merged
    periods: d,w,m,q,y
    desc: time_diff_as_string
  - name: PRs opened -> lgtmed -> approved -> merged (numer of hours)
    series_name_or_func: multi_row_multi_column
    sql: time_metrics
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: time_metrics
  - name: Suggested PR reviewers
    series_name_or_func: multi_row_multi_column
    sql: other_approver
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name:
      "Time before any comments or activities from someone other \
       than the author"
    series_name_or_func: multi_row_multi_column
    sql: first_non_author_activity
    periods: w,m,q,y
    desc: time_diff_as_string
    merge_series: first_non_author
  - name: Opened PRs age and count
    series_name_or_func: multi_row_multi_column
    sql: prs_age
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: prs_age
  - name: Closed Issues age and count
    series_name_or_func: multi_row_multi_column
    sql: issues_age
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    desc: time_diff_as_string
    merge_series: issues_age
  - name: PR comments percentiles
    series_name_or_func: single_row_multi_column
    sql: pr_comments
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name: Stargazers, watchers, forks
    series_name_or_func: multi_row_multi_column
    sql: watchers
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    merge_series: watchers
  - name: New contributors
    series_name_or_func: multi_row_multi_column
    sql: new_contributors
    periods: d,w,m,q,y
  - name: Episodic contributors
    series_name_or_func: multi_row_multi_column
    sql: episodic_contributors
    periods: d,w,m,q,y
    merge_series: episodic_contributors
  - name: New issues
    series_name_or_func: multi_row_multi_column
    sql: new_issues
    periods: d,w,m,q,y
  - name: Episodic issues
    series_name_or_func: multi_row_multi_column
    sql: episodic_issues
    periods: d,w,m,q,y
    merge_series: episodic_issues
  - name: SIG mentions using labels
    series_name_or_func: multi_row_single_column
    sql: labels_sig
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: KIND mentions using labels
    series_name_or_func: multi_row_single_column
    sql: labels_kind
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: SIG KIND mentions using labels
    series_name_or_func: multi_row_single_column
    sql: labels_sig_kind
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: sig_mentions_sig_kind
  - name: Issues closed broken down by SIG and kind
    series_name_or_func: multi_row_single_column
    sql: labels_sig_kind_closed
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: issues_closed_sig_kind
  - name: Bot commands usage
    series_name_or_func: multi_row_single_column
    sql: bot_commands
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: bot_commands
  - name: Open issues by milestone
    series_name_or_func: multi_row_single_column
    sql: open_issues_sigs_milestones
    periods: d
    merge_series: issues_milestones
  - name: Open PRs by milestone
    series_name_or_func: multi_row_single_column
    sql: open_prs_sigs_milestones
    periods: d
    merge_series: prs_milestones
  - name: Reviewers histogram
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_reviewers
  - name: Approvers histogram
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_approvers
  - name: PR authors companies histogram
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: hist_pr_companies
  - name: Project stats
    histogram: true
    annotations_ranges: true
    series_name_or_func: multi_row_single_column
    sql: project_stats
  - name: Company summaries
    sql: project_company_stats
    series_name_or_func: multi_row_single_column
    histogram: true
    annotations_ranges: true
  - name: Developer summaries
    sql: project_developer_stats
    series_name_or_func: multi_row_single_column
    histogram: true
    annotations_ranges: true
  - name: PR workload tabular
    sql: pr_workload_table
    series_name_or_func: multi_row_multi_column
    histogram: true
    annotations_ranges: true
    multi_value: true
  - name: PR workload chart
    series_name_or_func: multi_row_multi_column
    sql: pr_workload
    periods: d
    multi_value: true
  - name: Pull requests unique authors per repository
    series_name_or_func: multi_row_single_column
    sql: prs_authors
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
  - name: SIG mentions using texts
    series_name_or_func: multi_row_single_column
    sql: sig_mentions
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: SIG mentions categories using texts
    series_name_or_func: multi_row_single_column
    sql: sig_mentions_cats
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: PRs approved and awaiting approval
    series_name_or_func: multi_row_multi_column
    sql: prs_state
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    multi_value: true
  - name: PRs blocked for various reasons
    series_name_or_func: multi_row_multi_column
    sql: prs_blocked
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    multi_value: true
  - name: Companies stats & velocity
    series_name_or_func: multi_row_multi_column
    sql: company_activity
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: company_activity
  - name: Number of companies and developers contributing
    series_name_or_func: multi_row_multi_column
    sql: num_stats
    periods: d,w,m,q
    aggregate: 1,7,28
    skip: d,w7,m7,q7,w28,m28,q28
    merge_series: num_stats
  - name: Approvers in repository groups
    series_name_or_func: multi_row_single_column
    sql: approvers
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
  - name: User reviews
    series_name_or_func: multi_row_single_column
    sql: reviews_per_user
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    multi_value: true
    merge_series: user_reviews
  - name: OWNERS file
    series_name_or_func: owners_d
    sql: owners
    periods: d
  - name: GitHub activity
    series_name_or_func: events_h
    sql: events
    periods: h
